#include "esp_32.h"

Device ESP32_Dev_Kit_C_V4 = {
    "ESP32_Dev_Kit_C_V4",
    {{0,
      {"GPIO0",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-11"},
       PinMode::None,
       std::monostate{}}},
     {1,
      {"GPIO1",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {2,
      {"GPIO2",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-12"},
       PinMode::None,
       std::monostate{}}},
     {3,
      {"GPIO3",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {4,
      {"GPIO4",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-10"},
       PinMode::None,
       std::monostate{}}},
     {5,
      {"GPIO5",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {6,
      {"GPIO6",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {7,
      {"GPIO7",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {8,
      {"GPIO8",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {9,
      {"GPIO9",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {10,
      {"GPIO10",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {11,
      {"GPIO11",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {12,
      {"GPIO12",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-15"},
       PinMode::None,
       std::monostate{}}},
     {13,
      {"GPIO13",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM, PinMode::Analog_Input},
       {"RTC-14"},
       PinMode::None,
       std::monostate{}}},
     {14,
      {"GPIO14",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-16"},
       PinMode::None,
       std::monostate{}}},
     {15,
      {"GPIO15",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-13"},
       PinMode::None,
       std::monostate{}}},
     {16,
      {"GPIO16",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {17,
      {"GPIO17",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {18,
      {"GPIO18",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {19,
      {"GPIO19",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {21,
      {"GPIO21",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {22,
      {"GPIO22",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {23,
      {"GPIO23",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM},
       {},
       PinMode::None,
       std::monostate{}}},
     {25,
      {"GPIO25",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM, PinMode::Analog_Output},
       {"RTC-6"},
       PinMode::None,
       std::monostate{}}},
     {26,
      {"GPIO26",
       {PinMode::Digital_Input, PinMode::Digital_Output, PinMode::PWM, PinMode::Analog_Output},
       {"RTC-7"},
       PinMode::None,
       std::monostate{}}},
     {27,
      {"GPIO27",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-17"},
       PinMode::None,
       std::monostate{}}},
     {32,
      {"GPIO32",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-9"},
       PinMode::None,
       std::monostate{}}},
     {33,
      {"GPIO33",
       {PinMode::Digital_Input,
        PinMode::Digital_Output,
        PinMode::PWM,
        PinMode::Analog_Input,
        PinMode::Touch_Sensor},
       {"RTC-8"},
       PinMode::None,
       std::monostate{}}},
     {34,
      {"GPIO34",
       {PinMode::Digital_Input, PinMode::Analog_Input},
       {"RTC-4"},
       PinMode::None,
       std::monostate{}}},
     {35,
      {"GPIO35",
       {PinMode::Digital_Input, PinMode::Analog_Input},
       {"RTC-5"},
       PinMode::None,
       std::monostate{}}},
     {36,
      {"GPIO36",
       {PinMode::Digital_Input, PinMode::Analog_Input},
       {"RTC-0"},
       PinMode::None,
       std::monostate{}}},
     {39,
      {"GPIO39",
       {PinMode::Digital_Input, PinMode::Analog_Input},
       {"RTC-3"},
       PinMode::None,
       std::monostate{}}}}};